FROM alpine:latest
MAINTAINER Jason Wilder <mail@jasonwilder.com>

RUN apk -U add openssl

ENV DOCKER_HOST unix:///tmp/docker.sock

ADD dist/alpine-linux/amd64/docker-gen /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-gen"]
